import { delay } from "utils";
export const getServiceData = async () => {
  await delay(10);
  return {
    code: "0000",
    i18nFields: [
      "strategy.strategyName",
      "strategy.strategyDesc",
      "strategy.targetNames",
      "strategy.events.eventName",
      "strategy.treeNode.nodeName",
      "strategy.treeNode.policys.policyName",
      "strategy.treeNode.policys.nextTreeNode.nodeName",
      "strategy.treeNode.policys.nextTreeNode.policys.policyName",
      "strategy.treeNode.policys.nextTreeNode.policys.nextTreeNode.nodeName",
      "strategy.treeNode.policys.nextTreeNode.policys.nextTreeNode.policys.policyName",
      "strategy.treeNode.policys.nextTreeNode.policys.nextTreeNode.policys.nextTreeNode.nodeName",
      "strategy.treeNode.policys.nextTreeNode.policys.nextTreeNode.policys.nextTreeNode.policys.policyName",
      "strategy.treeNode.policys.nextTreeNode.policys.nextTreeNode.policys.nextTreeNode.policys.nextTreeNode.nodeName",
    ],
    strategy: {
      channel: "yunna",
      editStatus: "FINISH",
      endTime: 1622476799999,
      events: [
        { eventId: "online_consume_success", eventName: "线上商城消费成功" },
      ],
      exeCycle: "DAY",
      exeTime: "",
      limitNo: 1,
      planName: "5月热餐券包惊喜盲包",
      scopeType: "PART",
      startTime: 1619798400000,
      storeIds: ["SHP035"],
      storeNames: ["上海晶耀店"],
      strategyId: "MS20210426020812",
      strategyName: "自定义策略",
      strategyType: "event",
      targetIds: ["TG202008050002"],
      targetNames: ["用户激活"],
      treeNode: {
        cptType: "CHANCE",
        nodeId: "ROOT-JRXe5fvmb2-kaZBOxw5_n",
        nodeName: "概率",
        nodeType: "ROOT",
        policys: [
          {
            nextTreeNode: {
              cptType: "ACTION",
              nodeAdds: [
                {
                  bizName: "君乐宝慢醇/简醇酸奶2.5元券",
                  bizType: "coupon",
                  bizValue: "210426492",
                  nodeId: "node-Vs6gdZkszb3QUKMgOpsRc",
                  priority: 5,
                  strategyId: "MS20210426020812",
                },
                {
                  bizName: "三拼水果拼盘12.8元券",
                  bizType: "coupon",
                  bizValue: "210426491",
                  nodeId: "node-Vs6gdZkszb3QUKMgOpsRc",
                  priority: 5,
                  strategyId: "MS20210426020812",
                },
                {
                  bizName: "8元蛋糕券-咸芝士蛋糕",
                  bizType: "coupon",
                  bizValue: "210426489",
                  nodeId: "node-Vs6gdZkszb3QUKMgOpsRc",
                  priority: 5,
                  strategyId: "MS20210426020812",
                },
              ],
              nodeId: "node-Vs6gdZkszb3QUKMgOpsRc",
              nodeName: "营销内容",
              nodeType: "NORMAL",
            },
            nodeId: "ROOT-JRXe5fvmb2-kaZBOxw5_n",
            policyId: "TP20210427020934",
            policyName: "10%",
            policyValue: "10",
            strategyId: "MS20210426020812",
          },
          {
            nextTreeNode: {
              cptType: "ACTION",
              nodeAdds: [
                {
                  bizName: "三拼水果拼盘12.8元券",
                  bizType: "coupon",
                  bizValue: "210426491",
                  nodeId: "node-siXncgC5WllD1ooOxwwc9",
                  priority: 5,
                  strategyId: "MS20210426020812",
                },
                {
                  bizName: "天润百香果了酸奶3.99元券",
                  bizType: "coupon",
                  bizValue: "210426495",
                  nodeId: "node-siXncgC5WllD1ooOxwwc9",
                  priority: 5,
                  strategyId: "MS20210426020812",
                },
              ],
              nodeId: "node-siXncgC5WllD1ooOxwwc9",
              nodeName: "营销内容",
              nodeType: "NORMAL",
            },
            nodeId: "ROOT-JRXe5fvmb2-kaZBOxw5_n",
            policyId: "TP20210427020935",
            policyName: "20%",
            policyValue: "20",
            strategyId: "MS20210426020812",
          },
          {
            nextTreeNode: {
              cptType: "ACTION",
              nodeAdds: [
                {
                  bizName: "优诺优斯酸奶7.99元券（135g)",
                  bizType: "coupon",
                  bizValue: "210426493",
                  nodeId: "node-_iuBnA05GJolHKJN_s9a6",
                  priority: 5,
                  strategyId: "MS20210426020812",
                },
                {
                  bizName: "8.8元蛋糕券-巧克力酸奶风味盒子",
                  bizType: "coupon",
                  bizValue: "210427496",
                  nodeId: "node-_iuBnA05GJolHKJN_s9a6",
                  priority: 5,
                  strategyId: "MS20210426020812",
                },
              ],
              nodeId: "node-_iuBnA05GJolHKJN_s9a6",
              nodeName: "营销内容",
              nodeType: "NORMAL",
            },
            nodeId: "ROOT-JRXe5fvmb2-kaZBOxw5_n",
            policyId: "TP20210427020936",
            policyName: "10%",
            policyValue: "10",
            strategyId: "MS20210426020812",
          },
          {
            nextTreeNode: {
              cptType: "ACTION",
              nodeAdds: [
                {
                  bizName: "8.8元蛋糕券-阿华田风味蛋糕",
                  bizType: "coupon",
                  bizValue: "210426490",
                  nodeId: "node-o8RN2m2sF0jXecgO1UgHo",
                  priority: 5,
                  strategyId: "MS20210426020812",
                },
                {
                  bizName: "三拼水果拼盘12.8元券",
                  bizType: "coupon",
                  bizValue: "210426491",
                  nodeId: "node-o8RN2m2sF0jXecgO1UgHo",
                  priority: 5,
                  strategyId: "MS20210426020812",
                },
              ],
              nodeId: "node-o8RN2m2sF0jXecgO1UgHo",
              nodeName: "营销内容",
              nodeType: "NORMAL",
            },
            nodeId: "ROOT-JRXe5fvmb2-kaZBOxw5_n",
            policyId: "TP20210427020937",
            policyName: "10%",
            policyValue: "10",
            strategyId: "MS20210426020812",
          },
          {
            nextTreeNode: {
              cptType: "ACTION",
              nodeAdds: [
                {
                  bizName: "君乐宝涨芝士啦酸奶3.99元券",
                  bizType: "coupon",
                  bizValue: "210426494",
                  nodeId: "node-kxM5Czjjdjvvq1Pea0ADJ",
                  priority: 5,
                  strategyId: "MS20210426020812",
                },
              ],
              nodeId: "node-kxM5Czjjdjvvq1Pea0ADJ",
              nodeName: "营销内容",
              nodeType: "NORMAL",
            },
            nodeId: "ROOT-JRXe5fvmb2-kaZBOxw5_n",
            policyId: "TP20210427020938",
            policyName: "20%",
            policyValue: "20",
            strategyId: "MS20210426020812",
          },
        ],
      },
    },
    success: true,
  };
};
