
export const fakeData = {
  channel: "yunna",
  editStatus: "FINISH",
  endTime: 1621007999999,
  events: [{ eventId: "user_register", eventName: "注册成功" }],
  exeTime: "",
  limitNo: -1,
  planName: "test",
  scopeType: "ALL",
  startTime: 1620835200000,
  strategyId: "MS20210514023011",
  strategyName: "自定义策略",
  strategyType: "event",
  targetIds: ["TG202008050001"],
  targetNames: ["用户获取"],
  treeNode: {
    cptType: "CHANCE",
    nodeId: "ROOT-cCpjXO5XYoCn2j6yUf-Wx",
    nodeName: "概率",
    nodeType: "ROOT",
    policys: [
      {
        nextTreeNode: {
          cptSubType: "USER_STAGE",
          cptType: "TAG",
          nodeId: "node-E4Uqg50g-xY5uceP30bzC",
          nodeName: "生命周期",
          nodeType: "NORMAL",
          policys: [
            {
              nextTreeNode: {
                cptType: "ACTION",
                nodeAdds: [
                  {
                    bizName: "快餐荤菜立减5元",
                    bizType: "coupon",
                    bizValue: "210203379",
                    nodeId: "node-6Rm2Fyyv3t_d4ilLJNCe1",
                    priority: 5,
                    strategyId: "MS20210514023011",
                  },
                  {
                    bizName: "一荤两素一米饭20元-内部测试",
                    bizType: "coupon",
                    bizValue: "210422484",
                    nodeId: "node-6Rm2Fyyv3t_d4ilLJNCe1",
                    priority: 5,
                    strategyId: "MS20210514023011",
                  },
                ],
                nodeId: "node-6Rm2Fyyv3t_d4ilLJNCe1",
                nodeName: "营销内容",
                nodeType: "NORMAL",
              },
              nodeId: "node-E4Uqg50g-xY5uceP30bzC",
              policyId: "TP20210514023029",
              policyName: "潜客，新客",
              policyValue:
                '{"symbol":"in","value":"UTG21033110113,UTG21033110114"}',
              strategyId: "MS20210514023011",
            },
          ],
        },
        nodeId: "ROOT-cCpjXO5XYoCn2j6yUf-Wx",
        policyId: "TP20210514023028",
        policyName: "20%",
        policyValue: "20",
        strategyId: "MS20210514023011",
      },
      {
        nextTreeNode: {
          cptType: "ACTION",
          nodeAdds: [
            {
              bizName: "快餐荤菜立减5元",
              bizType: "coupon",
              bizValue: "210203379",
              nodeId: "node-nMcUZrP_G_1ca9OufFnN6",
              priority: 5,
              strategyId: "MS20210514023011",
            },
            {
              bizName: "一荤两素一米饭20元-内部测试",
              bizType: "coupon",
              bizValue: "210422484",
              nodeId: "node-nMcUZrP_G_1ca9OufFnN6",
              priority: 5,
              strategyId: "MS20210514023011",
            },
          ],
          nodeId: "node-nMcUZrP_G_1ca9OufFnN6",
          nodeName: "营销内容",
          nodeType: "NORMAL",
        },
        nodeId: "ROOT-cCpjXO5XYoCn2j6yUf-Wx",
        policyId: "TP20210514023030",
        policyName: "20%",
        policyValue: "20",
        strategyId: "MS20210514023011",
      },
      {
        nextTreeNode: {
          cptSubType: "SEX",
          cptType: "TAG",
          nodeId: "node-MWcNYCS7npN8A1t4XE3wH",
          nodeName: "性别",
          nodeType: "NORMAL",
          policys: [
            {
              nextTreeNode: {
                cptType: "ACTION",
                nodeAdds: [
                  {
                    bizName: "1",
                    bizType: "score",
                    bizValue: "1",
                    nodeId: "node-BmvXD8B2qTPTletuBcDo0",
                    priority: 5,
                    strategyId: "MS20210514023011",
                  },
                ],
                nodeId: "node-BmvXD8B2qTPTletuBcDo0",
                nodeName: "营销内容",
                nodeType: "NORMAL",
              },
              nodeId: "node-MWcNYCS7npN8A1t4XE3wH",
              policyId: "TP20210514023032",
              policyName: "男",
              policyValue: '{"symbol":"in","value":"UTG20M0922001"}',
              strategyId: "MS20210514023011",
            },
            {
              nextTreeNode: {
                cptType: "ACTION",
                nodeAdds: [
                  {
                    bizName: "1",
                    bizType: "score",
                    bizValue: "1",
                    nodeId: "node-272TtRnj8Y1qwG5gOK0xb",
                    priority: 5,
                    strategyId: "MS20210514023011",
                  },
                ],
                nodeId: "node-272TtRnj8Y1qwG5gOK0xb",
                nodeName: "营销内容",
                nodeType: "NORMAL",
              },
              nodeId: "node-MWcNYCS7npN8A1t4XE3wH",
              policyId: "TP20210514023033",
              policyName: "女",
              policyValue: '{"symbol":"in","value":"UTG20M0922002"}',
              strategyId: "MS20210514023011",
            },
          ],
        },
        nodeId: "ROOT-cCpjXO5XYoCn2j6yUf-Wx",
        policyId: "TP20210514023031",
        policyName: "20%",
        policyValue: "20",
        strategyId: "MS20210514023011",
      },
      {
        nextTreeNode: {
          cptType: "ACTION",
          nodeAdds: [
            {
              bizName: "不经常吃热餐的人诱导充值",
              bizType: "sms",
              bizValue: "CMC_SMS_MKT_20210416_059",
              nodeId: "node-6i6J_v0wm9Dt41OgNJUAe",
              priority: 6,
              strategyId: "MS20210514023011",
            },
          ],
          nodeId: "node-6i6J_v0wm9Dt41OgNJUAe",
          nodeName: "营销内容",
          nodeType: "NORMAL",
        },
        nodeId: "ROOT-cCpjXO5XYoCn2j6yUf-Wx",
        policyId: "TP20210514023034",
        policyName: "20%",
        policyValue: "20",
        strategyId: "MS20210514023011",
      },
      {
        nextTreeNode: {
          cptType: "ACTION",
          nodeAdds: [
            {
              bizName: "米饭客诉券",
              bizType: "coupon",
              bizValue: "210203382",
              nodeId: "node-xWmuMTH7omwOwGAzBSInR",
              priority: 5,
              strategyId: "MS20210514023011",
            },
          ],
          nodeId: "node-xWmuMTH7omwOwGAzBSInR",
          nodeName: "营销内容",
          nodeType: "NORMAL",
        },
        nodeId: "ROOT-cCpjXO5XYoCn2j6yUf-Wx",
        policyId: "TP20210514023035",
        policyName: "其它",
        policyValue: "OTHER",
        strategyId: "MS20210514023011",
      },
    ],
  },
};

export const fakeEventsData = [
  { eventId: "user_register", eventName: "注册成功" },
  { eventId: "consume_success", eventName: "门店消费成功" },
  { eventId: "online_consume_success", eventName: "线上商城消费成功" },
  { eventId: "recharge_success", eventName: "充值成功" },
];
